# Generated by Django 5.1 on 2024-08-30 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_aluno_curso'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Aluno',
        ),
    ]
