# Generated by Django 5.1 on 2024-08-31 02:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_aula'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aula',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aulas', to='core.curso'),
        ),
    ]
