# Generated by Django 5.1 on 2024-09-03 03:02

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_aula_curso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
